### ISSUE TITLE
Карусель новостей

### ISSUE THREAD

**Issue by yuriyant** [rambler-digital-solutions/rambler-ui#3]
Привет! Отличный набор компонентов! 
На rambler.ru присутствует довольно мощная, адаптивная карусель новостей. 
Не смог ее найти в пакете компонентов rambler-ui. 
Она не относится к набору компонентов или я не туда смотрел  ?

![adec2874f1](https://user-images.githubusercontent.com/1130955/42924951-1137db90-8b35-11e8-902f-d1df7df1202a.png)

**Comment by andrepolischuk** [comment]
@yuriyant в rambler-ui ее нет, тут более мелкие компоненты
